version: 2
orbs:
  python: circleci/python@1.5.0
  docker: circleci/docker@2.2.0

jobs:
  django-test:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          # テストに必要なコンテナを立ち上げ
          name: docker-compose up
          command: docker-compose up -d
      - run:
          # トラブルシューティング時、CircleCI の UI 上でコンテナの起動状況を確認できるようにコンテナ一覧を表示させる（趣味）
          name: docker ps
          command: docker ps
      - run:
          # Django の自動テスト
          # ここで失敗すると次の処理には進まないようになっているため、問題があるコードは本番環境に反映されないようになっている
          name: test
          command: docker-compose run python ./manage.py test
      - run:
          # コンテナを停止 (今思えばいらないかも？)
          name: docker-compose down
          command: docker-compose down

  build-and-push:
    environment:
      DOCKER_IMAGE: trinhchung/cicd
      DOCKER_TAG: 0.0.1
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG

      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  build-deploy:
    jobs:
      - django-test
      # - build-and-push:
      #     requires:
      #       - django-test
      #     filters:
      #       branches:
      #         only:
      #           - circleci-project-setup
